### ISSUE TITLE
Add more cases to the comparison Functions. Make them at least 2.

### ISSUE THREAD

**Issue by Sherlemious** [Sherlemious/IGCSE-CS-PC-Transpiler#11]
The Compare function currently supports only comparisons between two entities. This should be enhanced in order to make it possible to more than one comparison in one statement where the two comparisons are separated with a logic gate.

**Comment by AbdulMAbdi** [comment]
Hey, I would like to help with this

**Comment by Sherlemious** [comment]
Okay then, I think all that should be done is making a function in the Functions.py file that takes at least three parameters and uses the comp() function in the same file to perform comparison operations. It would be more than appreciated if you can make the number of comparisons at least 3.

**Comment by Sherlemious** [comment]
The parameters are basically two values to be compared, the comparison sign, and logic gates between more than one comparison
