### ISSUE TITLE
(FLK-E722) Do not use bare `except`, specify exception instead

### ISSUE THREAD

**Issue by Sherlemious** [Sherlemious/IGCSE-CS-PC-Transpiler#18]
## Description
Using `except` without a specific exception can be error-prone.

## Occurrences
There is 1 occurrence of this issue in the repository.
### Commands.py
```
322                to_be_eval += " " + str(V)
323        try:
324            to_be_eval = eval(to_be_eval)
325        except:
326            pass
327
328        if array:
```

**Comment by OBITORASU** [comment]
Would love to work on this one. Can I be assigned?

**Comment by Sherlemious** [comment]
Yes. the accepted errors are SyntaxError, NameError and value error but I'm not sure about whether this should be added.
