### ISSUE TITLE
Allow evaluation of the INT() function.

### ISSUE THREAD

**Issue by Sherlemious** [Sherlemious/IGCSE-CS-PC-Transpiler#23]

**Comment by Manishadhananjayalu** [comment]
Hello , I would like to contribute in these issue solving. Can I ? 
I'm new budding contributor , so can you help me by giving a chance to solve the issue.

**Comment by Sherlemious** [comment]
Yeah okay

**Comment by alexeacott-tech** [comment]
Can I work on this? Or has the previous commenter implemented it
